[package]
name = "inputbot"
version = "0.3.0"
authors = ["obv-mikhail <obv.mikhail@gmail.com>"]
description = "A library for creating global hotkeys, as well as emulating mouse and keyboard input."
documentation = "https://obv-mikhail.github.io/doc/inputbot/"
homepage = "https://github.com/obv-mikhail/inputbot"
repository = "https://github.com/obv-mikhail/inputbot"
readme = "README.md"
keywords = ["hotkey", "mouse", "keyboard", "input"]
categories = ["api-bindings"]
license = "MIT"

[dependencies]
lazy_static = "0.2"

[target.'cfg(windows)'.dependencies]
winapi = "0.2.8"
user32-sys = "0.2.0"

[target.'cfg(target_os="linux")'.dependencies.x11]
version = "2.14.0"
features = ["xlib", "xtest"]
