[package]
name = "inputbot"
version = "0.4.0"
authors = ["obv-mikhail <obv.mikhail@gmail.com>"]
description = "A library for creating global hotkeys, and emulating inputs. Unlike AutoHotkey, InputBot handles hotkeys concurrently and supports both Windows and Linux."
documentation = "https://docs.rs/inputbot"
homepage = "https://github.com/obv-mikhail/inputbot"
repository = "https://github.com/obv-mikhail/inputbot"
readme = "README.md"
keywords = ["hotkey", "mouse", "keyboard", "input", "bot"]
categories = ["api-bindings"]
license = "MIT"

[dependencies]
lazy_static = "0.2.11"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser"] }

[target.'cfg(target_os="linux")'.dependencies.x11]
version = "2.17.0"
features = ["xlib", "xtest"]
